version: '3'
services: 
  node:
    container_name: rest-service
    build: 
      context: .
    env_file: 
      - .env
    environment: 
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      - postgres
    restart: always
    command: npm run start

  postgres:
    container_name: postgres-db
    build: ./database
    env_file: 
      - .env
    environment: 
      PG_DATA: /var/lib/postgres/data
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always