version: '3'

services: 

  node:
    container_name: rest-service
    image: aparfimovich/rsschool-rest-service_node:latest
    env_file: 
      - .env
    build: 
      context: .
      dockerfile: Dockerfile.node
    ports:
      - ${PORT}:${PORT}
    environment: 
      - WORKDIR=${WORKDIR}
      - PORT=${PORT}
    volumes: 
      - .:${WORKDIR}
    networks: 
      - back
    depends_on:
      - postgres
    restart: on-failure
    command: ['npm','run','nest:start:dev']
      #['npm','run','start']

  postgres:
    container_name: postgres
    image: aparfimovich/rsschool-rest-service_postgres:latest
    env_file: 
      - .env
    build: 
      context: .
      dockerfile: Dockerfile.pg
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment: 
      PGDATA: ${WORKDIR}/data
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - ./database/pgdata:${WORKDIR}/data
    networks: 
      - back 
    restart: on-failure

networks: 

  # Network to connect rest-service container to postgres container
  back:
    driver: bridge
  
