# escape=`

FROM node:14-alpine

# Setup application folder
WORKDIR ${WORKDIR:-/usr/app}

# Copy dependencies config files into the workdir
COPY package*.json ./

# Install dependencies into the wirkdir
RUN npm ci

EXPOSE ${PORT:-4000}