# escape=`

FROM node:14-alpine

# Setup application folder
WORKDIR ${WORKDIR:-/usr/app}

# Copy dependencies config files into the workdir
COPY package*.json ./

# Install dependencies into the wirkdir
RUN npm install

EXPOSE ${PORT:-4000}

# Run script for checking db connection and running migration
ENTRYPOINT [ "sh", "entrypoint.sh" ]

CMD ["npm", "run", "start"]